import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/component/layouts/AppSidebar";
import React from "react";
import NextAuthProvider from "@/context/NextAuthProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "@/lib/authOptions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession (authOptions);
	console.log("dashLayout---->",session)
  
  if (session === null) {
		return redirect("/auth/signin");
	}

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
      <NextAuthProvider>
        <SidebarProvider style={{"--sidebar-width": "20rem","--sidebar-width-mobile": "20rem"} as React.CSSProperties}>
          <AppSidebar />
            <main>
              <SidebarTrigger />
              {children}
            </main>
        </SidebarProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
